repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: sort-simple-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
            - --markdown-linebreak-ext=md
      - id: check-toml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  - repo: local
    hooks:
      - id: format_scripts
        name: format scripts
        pass_filenames: false
        entry: black scripts
        language: system

      - id: lint_scripts
        name: lint scripts
        pass_filenames: false
        entry: task lint_scripts
        language: system

      # - id: compile_notebooks_check
      #   name: compile notebooks
      #   pass_filenames: false
      #   entry: task compile_notebooks_check -- --diff
      #   language: system

      - id: format_notebooks
        name: format notebooks
        pass_filenames: false
        entry: task format_notebooks -- --diff
        language: system

      - id: lint_notebooks
        name: lint notebooks
        pass_filenames: false
        entry: task lint_notebooks -- --diff
        language: system
