# https://taskfile.dev

version: '3'

vars:
  NOTEBOOK_DIFF:
    sh: git diff --cached --name-status | awk '$1 != "D" && $2 ~ /\.ipynb$/ { print $2 }' || true

tasks:
  format_notebooks:
    desc: "Format notebooks using prettier"
    silent: true
    cmds:
      - |
        if echo {{.CLI_ARGS}} | grep -q -- '--diff'; then
          FILES={{.NOTEBOOK_DIFF}}
          echo "Changed notebooks: $FILES"
          if [ -z "$FILES" ]; then
            echo "No changed notebooks to format."
            exit 0
          fi
          python scripts/format_ts_cells.py $FILES
        else
          python scripts/format_ts_cells.py .
        fi

  lint_notebooks:
    desc: "Lint notebooks using eslint"
    silent: true
    cmds:
      - |
        if echo {{.CLI_ARGS}} | grep -q -- '--diff'; then
          FILES={{.NOTEBOOK_DIFF}}
          echo "Changed notebooks: $FILES"
          if [ -z "$FILES" ]; then
            echo "No changed notebooks to lint."
            exit 0
          fi
          python scripts/lint_ts_cells.py $FILES
        else
          python scripts/lint_ts_cells.py .
        fi

  format_notebooks_check:
    desc: "Check notebooks formatting using prettier"
    silent: true
    cmds:
      - |
        if echo {{.CLI_ARGS}} | grep -q -- '--diff'; then
          FILES={{.NOTEBOOK_DIFF}}
          echo "Changed notebooks: $FILES"
          if [ -z "$FILES" ]; then
            echo "No changed notebooks to format."
            exit 0
          fi
          python scripts/format_ts_cells.py $FILES --check
        else
          python scripts/format_ts_cells.py . --check
        fi

  lint_notebooks_check:
    desc: "Check notebooks linting using eslint"
    silent: true
    cmds:
      - |
        if echo {{.CLI_ARGS}} | grep -q -- '--diff'; then
          FILES={{.NOTEBOOK_DIFF}}
          echo "Changed notebooks: $FILES"
          if [ -z "$FILES" ]; then
            echo "No changed notebooks to lint."
            exit 0
          fi
          python scripts/lint_ts_cells.py $FILES --check
        else
          python scripts/lint_ts_cells.py . --check
        fi

  compile_notebooks_check:
    desc: "Compile notebooks to python scripts"
    silent: true
    cmds:
      - |
        if echo {{.CLI_ARGS}} | grep -q -- '--diff'; then
          FILES={{.NOTEBOOK_DIFF}}
          echo "Changed notebooks: $FILES"
          if [ -z "$FILES" ]; then
            echo "No changed notebooks to compile."
            exit 0
          fi
          python scripts/compile_ts_cells.py $FILES
        else
          python scripts/compile_ts_cells.py .
        fi

  format_scripts:
    desc: "Format python scripts using black and isort"
    cmds:
      - black scripts
      - isort scripts

  lint_scripts:
    desc: "Lint python scripts using ruff and pyright"
    cmds:
      - ruff check scripts
      - pyright scripts

  notebooks:
    desc: "Format & lint notebooks"
    cmds:
      - task format_notebooks
      - task lint_notebooks
